### ISSUE TITLE
extra space in grub options

### ISSUE THREAD

**Issue by dmmagill** [OguzPastirmaci/misc#1]
https://github.com/OguzPastirmaci/misc/blob/3af62031f25a122d8016d77aa76704e91c9a9804/oci_rhel.sh#L15

Looks like there's an extra space in `iscsi_initiator=iqn.2015- 02.oracle.boot:instance"' >> /tmp/grub`

**Comment by OguzPastirmaci** [comment]
Good catch! Removed the extra space.
